# Generated by Django 5.0 on 2023-12-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_selectcandidatejob_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('selected', 'selected')], default='pending', max_length=20),
        ),
    ]
