# Generated by Django 5.0 on 2023-12-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_remove_candidateapplications_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='role',
            field=models.CharField(default='anything', max_length=100),
        ),
    ]
