# Generated by Django 5.0 on 2023-12-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_alter_candidateapplications_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplications',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
