# Generated by Django 5.0 on 2023-12-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_candidateapplications_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilehr',
            name='About',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profilehr',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
