# Generated by Django 5.0 on 2023-12-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_profilehr_about_profilehr_address_profilehr_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilehr',
            old_name='company_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='profilehr',
            old_name='About',
            new_name='qualifications',
        ),
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
