# Generated by Django 5.0 on 2023-12-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_profile'),
        ('hr', '0008_jobpost_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='myapplyjoblist',
            old_name='job',
            new_name='job_application',
        ),
        migrations.AlterField(
            model_name='issortlist',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.jobpost'),
        ),
        migrations.AlterField(
            model_name='myapplyjoblist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
