# Generated by Django 5.0 on 2023-12-29 15:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_rename_job_myapplyjoblist_job_application_and_more'),
        ('hr', '0008_jobpost_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myapplyjoblist',
            unique_together={('user', 'job_application')},
        ),
    ]
